name:                client
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- aeson
- base64-bytestring
- bytestring
- servant
- servant-client
- text
- http-client

library:
  source-dirs: src

executables:
  client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - client

tests:
  client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - client
