#!/bin/bash
set -euxo pipefail

docker run -v $PWD:/volume -v cargo-cache:/root/.cargo/registry --rm -t clux/muslrust cargo build --bin dag-cache --target x86_64-unknown-linux-musl --release
cp target/x86_64-unknown-linux-musl/release/dag-cache dag-cache/
cd dag-cache
docker build -t ishtar-orbital/dag-cache .
rm dag-cache
cd ..
