version: '3.3'
services:
  web:
    image: ishtar-orbital/notes-server:latest
    # build: .
    ports:
      - "3030:3030"
    links:
      - dag
    entrypoint:
      # TODO: structopts for this server instead of hardcoded
      - /notes-server
  dag:
    image: ishtar-orbital/dag-cache:latest
    expose:
      - 8080
    volumes:
      - "./dag-storage:/dag-storage"
    secrets:
      - honeycomb_key
    entrypoint:
      - /dag-cache
      - --honeycomb_key_file
      - /run/secrets/honeycomb_key
      - --fs_path
      - /dag-storage/sled.db

secrets:
   honeycomb_key:
     file: honeycomb_key.txt
