#!/bin/bash
set -euxo pipefail
tmp_dir=$(mktemp -d -t dag-store-XXXXXXXXXX)

echo "tmpdir is:" $tmp_dir

cargo run --bin dag-store -- --honeycomb_key_file honeycomb.key \
              --fs_path $tmp_dir &
cargo run --bin notes-server -- --honeycomb_key_file honeycomb.key \
                 --dag_store_url http://localhost:8088 \
                 -p 3030 &

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
wait
