#!/bin/bash
set -euxo pipefail

cargo run --bin dag-store -- --honeycomb_key_file honeycomb.key \
              --fs_path tmpdir &
cargo run --bin notes-server -- --honeycomb_key_file honeycomb.key \
                 --dag_store_url http://localhost:8088 \
                 -p 3030 &

# bin/dag-store --honeycomb_key_file docker/honeycomb_key.txt \
#                 --fs_path tmpdir &
# bin/notes-server --honeycomb_key_file docker/honeycomb_key.txt \
#                    --dag_store_url http://localhost:8088 \
#                    -p 3030 \
#                    --static_dir web &

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
wait
