#!/bin/bash
set -euxo pipefail


target/release/dag-store --jaeger-agent localhost:6831 \
              --fs_path tmpdir &
target/release/notes-server --jaeger-agent localhost:6831 \
                 --dag_store_url http://localhost:8088 \
                 -p 3030 &

# bin/dag-store --honeycomb_key_file docker/honeycomb_key.txt \
#                 --fs_path tmpdir &
# bin/notes-server --honeycomb_key_file docker/honeycomb_key.txt \
#                    --dag_store_url http://localhost:8088 \
#                    -p 3030 \
#                    --static_dir web &

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
wait
