[package]
name = "notes-types"
version = "0.1.0"
authors = ["pk <pkinsky@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"

dag-store-types = { path = "../dag-store-types", features = ["minimal"]}