[package]
name = "notes-server"
version = "0.1.0"
authors = ["pk <pkinsky@gmail.com>"]
edition = "2018"

[dependencies]
gotham = "0.4"
gotham_derive = "0.4"

hyper = "0.12"
mime = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio = "0.2.0-alpha.6"
futures-preview = { version = "0.3.0-alpha.14", features = ["compat"] }

tonic = "0.1.0-alpha.6"
dag-cache = { path = "../dag-cache" }